pipeline:
  docker-image:
    image: plugins/docker
    tags: latest
    dockerfile: Dockerfile
    repo: docker.netsoc.co/strum355/2bot
    registry: docker.netsoc.co
    secrets: [ docker_username, docker_password ]
branches: master