pipeline:
  lint:
    image: golang
    commands:
      - bash -c "if [[ \$(gofmt -l *.go) ]]; then gofmt -l *.go; exit 1; fi"
    when:
      event: [ push, pull_request ]

  docker-image:
    image: plugins/docker
    tags: latest
    dockerfile: Dockerfile
    repo: docker.netsoc.co/strum355/2bot
    registry: docker.netsoc.co
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      status: [ success ]

  discord-notif:
    image: appleboy/drone-discord
    username: 2Bot CI
    avatar_url: https://noahsc.xyz/public_images/drone.png
    secrets: [discord_webhook_id, discord_webhook_token]
    color: "#42f483"
    message: >
      {{#success build.status}}
        2Bot successfully built and pushed. Build num {{build.number}}.
      {{else}}
        2Bot failed to build. Build num {{build.number}}.
      {{/success}}    
    when:
      branch: master
