pipeline:
  docker-image:
    image: plugins/docker
    tags: latest
    dockerfile: Dockerfile
    repo: docker.netsoc.co/strum355/2bot
    registry: docker.netsoc.co
    secrets: [ docker_username, docker_password ]
  discord-notif:
    image: appleboy/drone-discord
    username: 2Bot CI
    avatar_url: https://cdn.worldvectorlogo.com/logos/drone.svg
    message: "test message"
    secrets: [ discord_webhook_id, discord_webhook_token ]
branches: master
