language: go

go:
  - 1.8
  - 1.9
  - master

install:
  - go get github.com/bwmarrin/discordgo
  - go get github.com/Strum355/dgwidgets
  - go get github.com/jonas747/dca
  - go get github.com/rylio/ytdl
